apiVersion: v1
kind: ConfigMap
metadata:
  name: eks-bb-orchestrator
  namespace: eks-bb
data:
  TZ: "Asia/Kolkata"
  REGION: "ap-south-1"
  INPT_QUEUE_URL : "https://sqs.ap-south-1.amazonaws.com/902812008909/orchestrator"
  POLL_FREQUENCY: "20"
  ORCHESTRATION: '{"Orders" : {"SUCCESS" : "https://sqs.ap-south-1.amazonaws.com/902812008909/inventory-input"},"Inventory" : {"FAIL" : "https://sqs.ap-south-1.amazonaws.com/902812008909/orders-rollback"}}'