apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name:   bb-cluster
    region: ap-south-1
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
    